# train a simple linear model using Numpy

- supervised learning
- regression

In [19]:
import numpy as np

## Dataset

In [20]:
X = np.array([
    [170, 70, 25],
    [180, 80, 30],
    [160, 60, 20]
])

y = np.array([300, 400, 250])

| Height | Weight | Age    | Price  |
| ------ | ------ | ------ | ------ |
| 170    | 70     | 25     | 300    |
| 180    | 80     | 30     | 400    |
| 160    | 60     | 20     | 250    |

## First Forward

In [21]:
first_weights = np.random.randn(3) # Model weight, not the weight in the data
first_bias =  np.random.randn(1)
first_weights, first_bias

(array([-0.45720361,  0.92001644,  0.01940547]), array([0.41907029]))

In [23]:
wxn = X * first_weights
wxn

array([[-77.72461401,  64.40115069,   0.48513677],
       [-82.29665013,  73.60131508,   0.58216412],
       [-73.15257789,  55.20098631,   0.38810941]])

In [25]:
sigma_wxn = np.sum(wxn, axis=1)
sigma_wxn

array([-12.83832655,  -8.11317093, -17.56348217])

In [27]:
y_pred = sigma_wxn + first_bias
y_pred

array([-12.41925626,  -7.69410064, -17.14441188])

| y_true | y_pred |
| ------ | ------ |
| 300    | -12.41 |
| 400    | -7.69  |
| 250    | -17.14 |

## Backpropagation

### Loss Function (MSE)

In [34]:
loss = np.sum((y - y_pred) ** 2) / len(y_pred) # MSE = sigma(y_true - y_pred)**2 / N
loss

np.float64(111728.80272410746)