# train a simple linear model using Numpy

- supervised learning
- regression

In [65]:
import numpy as np
import pandas as pd # for visualization

## Dataset

In [53]:
X = np.array([
    [170, 70, 25],
    [180, 80, 30],
    [160, 60, 20]
])

y = np.array([300, 400, 250])

In [71]:
# visualize dataset
dataset = {
  "Height": X[:, 0],
  "Weight": X[:, 1],
  "Age": X[:, 2],
  "Price": y
}

df = pd.DataFrame(dataset)
print(df)

   Height  Weight  Age  Price
0     170      70   25    300
1     180      80   30    400
2     160      60   20    250


## First Forward

In [54]:
first_weights = np.random.randn(3) # Model weight, not the weight in the data
first_bias =  np.random.randn(1)
first_weights, first_bias

(array([ 0.59149762, -0.25768781,  1.37552417]), array([-1.3276262]))

In [64]:
y_pred = X.dot(first_weights) + first_bias
y_pred

array([115.57692647, 125.79264542, 105.36120752])

In [70]:
y_table = {
  "y_true": y,
  "y_pred": y_pred
}

#load data into a DataFrame object:
ydf = pd.DataFrame(y_table)

print(ydf)

   y_true      y_pred
0     300  115.576926
1     400  125.792645
2     250  105.361208


## Backpropagation

### Loss Function (MSE)

In [58]:
loss = np.mean((y - y_pred) ** 2) # MSE = sigma(y_true - y_pred)**2 / N
loss

np.float64(43373.974547885766)

### Optimizer (Gradient Descent)

In [61]:
lr = 0.000001

In [62]:
# w_new = w_old - lr * gradient
w_new = first_weights - lr * (-2 * X.T.dot(y - y_pred) / len(y))
b_new = first_bias - lr * (-2 * np.mean(y - y_pred))

w_new, b_new


(array([ 0.66073192, -0.22867146,  1.38601056]), array([-1.32722402]))